# Generated by Django 5.1.4 on 2024-12-27 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_message_image_message_video_room_favorites_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="likes",
        ),
        migrations.AddField(
            model_name="message",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
