# Generated by Django 5.1.4 on 2024-12-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorites_rooms",
            field=models.ManyToManyField(
                blank=True, related_name="favorited_by", to="base.room"
            ),
        ),
    ]
