# Generated by Django 5.1.3 on 2024-12-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_announcement_updated_at_topic_created_topic_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_muted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="mute_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mute_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
