# Generated by Django 5.1.4 on 2024-12-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="encrypted_body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="encryption_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
