# Generated by Django 5.1.4 on 2024-12-28 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_room_is_encrypted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={"verbose_name": "公告", "verbose_name_plural": "公告列表"},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["-updated", "created"],
                "verbose_name": "消息",
                "verbose_name_plural": "消息列表",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name": "通知", "verbose_name_plural": "通知列表"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ["-updated", "created"],
                "verbose_name": "房间",
                "verbose_name_plural": "房间列表",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"verbose_name": "话题", "verbose_name_plural": "话题列表"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "用户", "verbose_name_plural": "用户列表"},
        ),
        migrations.AddField(
            model_name="room",
            name="is_hidden",
            field=models.BooleanField(default=False, verbose_name="是否隐藏"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="公告作者",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content",
            field=models.TextField(verbose_name="公告内容"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=200, verbose_name="公告标题"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="message",
            name="body",
            field=models.TextField(verbose_name="消息内容"),
        ),
        migrations.AlterField(
            model_name="message",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="message",
            name="encrypted_body",
            field=models.TextField(blank=True, null=True, verbose_name="加密消息内容"),
        ),
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/", verbose_name="附加图片"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="点赞用户",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="base.room",
                verbose_name="所在房间",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="发送用户",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to="videos/", verbose_name="附加视频"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="是否已读"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.CharField(max_length=255, verbose_name="通知内容"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="时间戳"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="房间描述"),
        ),
        migrations.AlterField(
            model_name="room",
            name="encryption_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="加密密钥"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorite_rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="收藏的房间",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="host",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="房间主持人",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_encrypted",
            field=models.BooleanField(default=False, verbose_name="是否加密"),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=200, verbose_name="房间名称"),
        ),
        migrations.AlterField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participants",
                to=settings.AUTH_USER_MODEL,
                verbose_name="参与者",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.topic",
                verbose_name="房间话题",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=200, verbose_name="话题名称"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatar.svg", null=True, upload_to="", verbose_name="头像"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(null=True, verbose_name="个人简介"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="favorites_rooms",
            field=models.ManyToManyField(
                blank=True,
                related_name="favorited_by",
                to="base.room",
                verbose_name="收藏的房间",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_muted",
            field=models.BooleanField(default=False, verbose_name="是否静音"),
        ),
        migrations.AlterField(
            model_name="user",
            name="mute_reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="静音原因"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mute_until",
            field=models.DateTimeField(blank=True, null=True, verbose_name="静音至"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200, null=True, verbose_name="姓名"),
        ),
        migrations.AlterField(
            model_name="user",
            name="score",
            field=models.IntegerField(default=0, verbose_name="积分"),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "friends",
                    models.ManyToManyField(
                        blank=True,
                        related_name="friends_list",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
