# Generated by Django 5.1.3 on 2024-12-30 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_userroom"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserRoom",
        ),
    ]
