# Generated by Django 5.1.3 on 2025-01-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_roomhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_disabled",
            field=models.BooleanField(default=False),
        ),
    ]
